name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"

  build-linux-x64-x86:
    runs-on: ubuntu-latest
    needs: set-date

    steps:
      # https://learn.microsoft.com/zh-cn/dotnet/core/deploying/native-aot/cross-compile
      - run: |
          sudo dpkg --add-architecture i386
          sudo bash -c 'cat > /etc/apt/sources.list.d/i386.list <<EOF
          deb [arch=i386] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted
          deb [arch=i386] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted
          deb [arch=i386] http://ports.ubuntu.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
          EOF'
          sudo sed -i -e 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
          sudo sed -i -e 's/deb mirror/deb [arch=amd64] mirror/g' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y curl wget libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev clang llvm binutils gcc zlib1g-dev
      
      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Publish [linux]
        run: |
          dotnet publish BBDown -r linux-x64 -c Release -o artifact
          dotnet publish BBDown -r linux-x86 -c Release -o artifact-x86

      - name: Package [linux]
        run: |
          cd artifact
          zip ../BBDown_${{ needs.set-date.outputs.date }}_linux-x64.zip BBDown
          cd ../artifact-x86
          zip ../BBDown_${{ needs.set-date.outputs.date }}_linux-x86.zip BBDown

      - name: Upload Artifact [linux-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_linux-x64
          path: BBDown_${{ needs.set-date.outputs.date }}_linux-x64.zip

      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_linux-x86
          path: BBDown_${{ needs.set-date.outputs.date }}_linux-x86.zip
          
